parallel e2e and operator build

diff --git a/.github/workflows/e2e-build.yaml b/.github/workflows/e2e-build.yaml
--- a/.github/workflows/e2e-build.yaml
+++ b/.github/workflows/e2e-build.yaml
@@ -12,7 +12,7 @@ on:
 #     - master
 #     - release-*
 jobs:
-  image-build:
+  operator-image-build:
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
@@ -55,16 +55,6 @@ jobs:
         run: |
           echo $GOCACHE
           make build
-          make e2e-build
-          [ -d tests/images/e2e/tidb-operator ] && rm -r tests/images/e2e/tidb-operator || true
-          [ -d tests/images/e2e/tidb-cluster ] && rm -r tests/images/e2e/tidb-cluster || true
-          [ -d tests/images/e2e/tidb-backup ] && rm -r tests/images/e2e/tidb-backup || true
-          [ -d tests/images/e2e/manifests ] && rm -r tests/images/e2e/manifests || true
-          cp -r charts/tidb-operator tests/images/e2e
-          cp -r charts/tidb-cluster tests/images/e2e
-          cp -r charts/tidb-backup tests/images/e2e
-          cp -r charts/tidb-drainer tests/images/e2e
-          cp -r manifests tests/images/e2e
         working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
 
       - name: Login to GitHub Container Registry
@@ -73,13 +63,6 @@ jobs:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ secrets.CR_PAT }}
-
-      # # In this step, this action saves a list of existing images,
-      # # the cache is created without them in the post run.
-      # # It also restores the cache if it exists.
-      # - uses: satackey/action-docker-layer-caching@v0.0.11
-      #   # Ignore the failure of a step and avoid terminating the job.
-      #   continue-on-error: true
 
       - name: Build and push
         uses: docker/build-push-action@v2
@@ -101,6 +84,62 @@ jobs:
           tags: |
             ghcr.io/handlerww/tidb-operator/tidb-operator:${{ github.sha }}
 
+      - name: Get matrix jobs
+        id: set-matrix
+        run: |
+          echo "::set-output name=matrix::{\"include\":[{\"job\":\"[Feature:.CDC]\"}]}"
+        # run: |
+        #   echo "::set-output name=matrix::{\"include\":[{\"job\":\"when.deploy,.scale,.update.config.should.work.in.v3.1.1\"},{\"job\":\"when.stores.number.is.equal.to.3.forbid.to.scale.in.TiKV.and.the.state.of.all.stores.are.up\"},{\"job\":\"TiKV.should.mount.multiple.pvc\"},{\"job\":\"should.adopt.helm.created.pump.with.TidbCluster.CR\"},{\"job\":\"should.keep.tidb.service.in.sync\"},{\"job\":\"should.upgrade.TidbCluster.with.webhook.enabled\"},{\"job\":\"[Feature:.AutoFailover].should.clear.TiDB.failureMembers.when.scale.TiDB.to.zero\"},{\"job\":\"should.ensure.changing.TiDB.service.annotations.won't.change.TiDB.service.type.NodePort\"},{\"job\":\"[Feature:.AutoScaling].should.auto.scale.TiKV.pods\"},{\"job\":\"[Feature:.Heterogeneous.Cluster].should.join.heterogeneous.cluster.into.an.existing.cluster\"},{\"job\":\"should.manage.tidb.monitor.normally\"},{\"job\":\"can.be.paused.and.resumed\"},{\"job\":\"should.switch.between.pod.network.and.host.network\"},{\"job\":\"should.backup.and.restore.TiDB.Cluster\"},{\"job\":\"[Feature:.CDC]\"},{\"job\":\"when.deploy,.scale,.update.config.should.work.in.v4.0.4\"},{\"job\":\"should.migrate.from.helm.to.CR\"},{\"job\":\"[Feature:.TLS].should.enable.TLS.for.MySQL.Client.and.between.Heterogeneous.TiDB.components\"},{\"job\":\"[Feature:.AutoScaling].should.auto.scale.TiDB.pods\"},{\"job\":\"[Feature:.TLS].should.enable.TLS.for.MySQL.Client.and.between.TiDB.components\"},{\"job\":\"Up.–.tidb-operator\"},{\"job\":\"DumpClusterLogs.–.tidb-operator\"},{\"job\":\"Down.–.tidb-operator\"}]}"
+  e2e-image-build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set up Go 1.13
+        uses: actions/setup-go@v1
+        with:
+          go-version: 1.13
+        id: go
+
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          path: go/src/github.com/${{ github.repository }}
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
+
+      - uses: actions/cache@v2
+        with:
+          path: |
+            ~/go/pkg/mod
+            ~/.cache/go-build
+            go/src/github.com/${{ github.repository }}/go/pkg/mod
+            go/src/github.com/${{ github.repository }}/.cache/go-build
+          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+          restore-keys: |
+            ${{ runner.os }}-go-
+
+      - name: Build binary
+        run: |
+          make e2e-build
+          [ -d tests/images/e2e/tidb-operator ] && rm -r tests/images/e2e/tidb-operator || true
+          [ -d tests/images/e2e/tidb-cluster ] && rm -r tests/images/e2e/tidb-cluster || true
+          [ -d tests/images/e2e/tidb-backup ] && rm -r tests/images/e2e/tidb-backup || true
+          [ -d tests/images/e2e/manifests ] && rm -r tests/images/e2e/manifests || true
+          cp -r charts/tidb-operator tests/images/e2e
+          cp -r charts/tidb-cluster tests/images/e2e
+          cp -r charts/tidb-backup tests/images/e2e
+          cp -r charts/tidb-drainer tests/images/e2e
+          cp -r manifests tests/images/e2e
+        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
+
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v1
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.CR_PAT }}
+
       - name: Build and push
         uses: docker/build-push-action@v2
         with:
@@ -111,15 +150,8 @@ jobs:
           tags: |
             ghcr.io/handlerww/tidb-operator/tidb-operator-e2e:${{ github.sha }}
 
-      - name: Get matrix jobs
-        id: set-matrix
-        run: |
-          echo "::set-output name=matrix::{\"include\":[{\"job\":\"[Feature:.CDC]\"}]}"
-        # run: |
-        #   echo "::set-output name=matrix::{\"include\":[{\"job\":\"when.deploy,.scale,.update.config.should.work.in.v3.1.1\"},{\"job\":\"when.stores.number.is.equal.to.3.forbid.to.scale.in.TiKV.and.the.state.of.all.stores.are.up\"},{\"job\":\"TiKV.should.mount.multiple.pvc\"},{\"job\":\"should.adopt.helm.created.pump.with.TidbCluster.CR\"},{\"job\":\"should.keep.tidb.service.in.sync\"},{\"job\":\"should.upgrade.TidbCluster.with.webhook.enabled\"},{\"job\":\"[Feature:.AutoFailover].should.clear.TiDB.failureMembers.when.scale.TiDB.to.zero\"},{\"job\":\"should.ensure.changing.TiDB.service.annotations.won't.change.TiDB.service.type.NodePort\"},{\"job\":\"[Feature:.AutoScaling].should.auto.scale.TiKV.pods\"},{\"job\":\"[Feature:.Heterogeneous.Cluster].should.join.heterogeneous.cluster.into.an.existing.cluster\"},{\"job\":\"should.manage.tidb.monitor.normally\"},{\"job\":\"can.be.paused.and.resumed\"},{\"job\":\"should.switch.between.pod.network.and.host.network\"},{\"job\":\"should.backup.and.restore.TiDB.Cluster\"},{\"job\":\"[Feature:.CDC]\"},{\"job\":\"when.deploy,.scale,.update.config.should.work.in.v4.0.4\"},{\"job\":\"should.migrate.from.helm.to.CR\"},{\"job\":\"[Feature:.TLS].should.enable.TLS.for.MySQL.Client.and.between.Heterogeneous.TiDB.components\"},{\"job\":\"[Feature:.AutoScaling].should.auto.scale.TiDB.pods\"},{\"job\":\"[Feature:.TLS].should.enable.TLS.for.MySQL.Client.and.between.TiDB.components\"},{\"job\":\"Up.–.tidb-operator\"},{\"job\":\"DumpClusterLogs.–.tidb-operator\"},{\"job\":\"Down.–.tidb-operator\"}]}"
-
   e2e-cases:
-    needs: ["image-build"]
+    needs: ["operator-image-build","e2e-image-build"]
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
